[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.389 s <<< FAILURE! -- in osplus.pkp.dto.plugin.RestDtoGeneratorPluginTest
[ERROR] osplus.pkp.dto.plugin.RestDtoGeneratorPluginTest.testSuccessfulGeneration -- Time elapsed: 0.321 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception thrown: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:84)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:53)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:36)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3199)
	at osplus.pkp.dto.plugin.RestDtoGeneratorPluginTest.testSuccessfulGeneration(RestDtoGeneratorPluginTest.java:76)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at osplus.pkp.dto.plugin.RestDtoGeneratorPlugin.insertRestInPackage(RestDtoGeneratorPlugin.java:170)
	at osplus.pkp.dto.plugin.RestDtoGeneratorPlugin.generateDto(RestDtoGeneratorPlugin.java:106)
